import './global.css';

// Force dynamic rendering for all pages
export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Welcome to parent-app',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
